authors:
  hantang:
    name: Hantang
    description: original
    avatar: https://github.com/hantang.png
  others:
    name: Anonymous
    description: reprinted
    avatar: https://github.com/github.png
