name: Deploy Blog

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 3/6"

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.x

    steps:
      - name: Checkout blog
        uses: actions/checkout@v4
        with:
          repository: hantang/void
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1
          ref: ${{ github.ref }}
          submodules: 'true'
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # - uses: pnpm/action-setup@v4
      #   with:
      #     version: latest
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: latest
      # - name: Install Python dependencies
      #   run: pip install -r requirements.txt
      - name: Build mkdocs site
        run: bash ./deploy-all.sh
      - name: Setup pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
